# frozen_string_literal: true

require 'couchbase-orm'

class Doc < CouchbaseOrm::Base
  attribute :title
end

describe 'CouchbaseOrm::Changeable' do
  it 'should have empty changes after loading a record from db' do
    doc = Doc.create(title: 'Test')
    expect(doc.changes).to be_empty
    doc = Doc.find(doc.id)
    expect(doc.changes).to be_empty
  end

  describe 'per-attribute dirty methods generated by create_dirty_methods' do
    # `changes_applied` runs the same in-memory bookkeeping create/update
    # triggers after a save (no DB round trip needed to exercise it).
    let(:doc) do
      Doc.new(title: 'initial').tap do |d|
        d.title = 'Test'
        d.changes_applied
      end
    end

    it 'exposes the change made in the last save' do
      expect(doc.changed?).to be false # cleared by changes_applied
      expect(doc.title_change).to be_nil # no change pending right now
      expect(doc.will_save_change_to_title?).to be false
      expect(doc.title_previously_was).to eq('initial')
      expect(doc.title_before_last_save).to be_nil # only set by a real save, not by changes_applied alone
      expect(doc.title_previously_changed?).to be true
      expect(doc.title_previous_change).to eq(['initial', 'Test'])
    end

    it 'exposes the change during the save that triggered it, with an explicit from/to' do
      expect(doc.saved_change_to_title?(from: 'initial')).to be true
      expect(doc.saved_change_to_title?(to: 'Test')).to be true
      expect(doc.saved_change_to_title?(from: 'initial', to: 'Test')).to be true
      expect(doc.saved_change_to_title?(from: 'nope')).to be false
    end

    it 'can flag an attribute as about to change, and reset it back' do
      expect { doc.title_will_change! }.not_to raise_error
      expect { doc.reset_title! }.not_to raise_error
    end

    it 'falls back to nil for an attribute that was never saved' do
      expect(Doc.new.title_previously_was).to be_nil
    end
  end
end
